// The illustration asset map: which files exist for each asset in the manifest
// and how a page should reference them.
//
// scripts/generate-illustrations.ts writes a PNG master per {asset × mode}
// and then encodes the WebP variants named here. The pages load only the
// variants; the masters are committed so a variant can be re-encoded without
// paying to draw the picture again, exactly as the hub comic does
// (docs/adr/0003-the-comic-is-private.md).
//
// Every reference goes through this file so a missing or renamed file is a
// type error at the call site rather than a silent blank rectangle in
// production: an <img> with width and height reserves its box whether or not
// anything arrives, which is the failure recorded as IX-013.
import { illustrations, type IllustrationPrompt, type ThemeMode } from "./image-prompts";

export type IllustrationId = (typeof illustrations)[number]["id"];

/** Pixel dimensions the API produces for each declared size. "auto" is not
 *  used by any asset in the manifest; it is pinned to the wide shape so the
 *  type stays total. */
export const SIZE_PX: Record<IllustrationPrompt["size"], { w: number; h: number }> = {
  "1536x1024": { w: 1536, h: 1024 },
  "1024x1536": { w: 1024, h: 1536 },
  "1024x1024": { w: 1024, h: 1024 },
  auto: { w: 1536, h: 1024 },
};

/** The widths encoded per shape. A wide picture is never displayed above
 *  ~1100 CSS px (the console column is 1080) and a spot illustration never
 *  above 420, so these cover a 2x display without a third file. */
export const VARIANT_WIDTHS: Record<IllustrationPrompt["size"], readonly number[]> = {
  "1536x1024": [768, 1536],
  "1024x1536": [512, 1024],
  "1024x1024": [512, 1024],
  auto: [768, 1536],
};

/** Alt text per asset. Pictures that sit behind live text are decorative and
 *  get the empty string, so a screen reader skips them rather than describing
 *  a workbench before every page title. The mascot spot art is content and is
 *  described. */
export const ALT: Record<IllustrationId, string> = {
  "auth-hero": "",
  "dashboard-hero": "",
  "card-clients": "",
  "card-engineering": "",
  "card-activity": "",
  "card-publish": "",
  mascot: "A small boxy repair robot with a glowing light-bulb head, holding a wrench.",
  "empty-state":
    "The console's repair-bot mascot sitting on the edge of an empty workbench, waiting for something to do.",
  "error-404":
    "The console's repair-bot mascot scratching its head beside a gadget that has come apart, a spring sticking out.",
  "texture-paper": "",
};

const BY_ID = new Map<string, IllustrationPrompt>(illustrations.map((a) => [a.id, a]));

export function illustration(id: IllustrationId): IllustrationPrompt {
  const a = BY_ID.get(id);
  if (!a) throw new Error(`No illustration named ${id}`);
  return a;
}

/** Public URL of the PNG master for an asset in a mode. `out` in the manifest
 *  is a repo path under public/, so the URL is that path with public/ removed. */
export function masterPath(a: IllustrationPrompt, mode: ThemeMode): string {
  return a.out.replace("{mode}", mode);
}
export function masterUrl(a: IllustrationPrompt, mode: ThemeMode): string {
  return masterPath(a, mode).replace(/^public/, "");
}

/** The WebP variants for an asset in a mode, smallest first, so the last one
 *  is the plain `src` fallback for anything that ignores srcSet. */
export function variantsFor(a: IllustrationPrompt, mode: ThemeMode): { url: string; path: string; w: number }[] {
  return VARIANT_WIDTHS[a.size].map((w) => {
    const path = masterPath(a, mode).replace(/\.png$/, `-${w}.webp`);
    return { path, url: path.replace(/^public/, ""), w };
  });
}

/** Everything an <img> needs for one asset in one mode. */
export function imageProps(id: IllustrationId, mode: ThemeMode): {
  src: string;
  srcSet: string;
  width: number;
  height: number;
  alt: string;
} {
  const a = illustration(id);
  const variants = variantsFor(a, mode);
  const px = SIZE_PX[a.size];
  return {
    src: variants[variants.length - 1]!.url,
    srcSet: variants.map((v) => `${v.url} ${v.w}w`).join(", "),
    width: px.w,
    height: px.h,
    alt: ALT[id],
  };
}

/** The assets that are generated by default. The paper texture is optional in
 *  the manifest and the app draws its grain with SVG feTurbulence instead, so
 *  it is skipped unless asked for. */
export const DEFAULT_ASSETS: readonly IllustrationPrompt[] = illustrations.filter(
  (a) => a.id !== "texture-paper",
);

/** Files every default asset must have on disk for the pages to render fully.
 *  Used by the generation script's summary and by the gating spec. */
export function expectedFiles(): string[] {
  const modes: ThemeMode[] = ["light", "dark"];
  return DEFAULT_ASSETS.flatMap((a) =>
    modes.flatMap((m) => [masterPath(a, m), ...variantsFor(a, m).map((v) => v.path)]),
  );
}
