// QA suite — landing-page blog article publishing (/api/publish/article).
// Runs against the real OpenAI + GitHub backends with dummy data; every PR
// and branch it creates is closed/deleted in teardown.
//
//   npx tsx --env-file=.env.local scripts/tests/suite-article.ts
import { callRoute } from "../invoke";
import { test, expect, note, finish, landingFile, closePr, deleteBranch, openPrFor } from "./harness";

const SLUG = "qa-suite-article";
const BRANCH = `content/article-${SLUG}`;

const TITLE = `QA Suite: "Quoted" Titles & Ampersands — a test`;
const BODY = [
  "This is a dummy article generated by the console QA suite. It exists to prove the publish pipeline end to end and is never merged.",
  "",
  "## A section heading",
  "",
  "Some paragraph text with **bold**, `inline code`, and a [link](https://luminary-dev.xyz).",
  "",
  "```ts",
  'const answer = "forty-two";',
  "```",
  "",
  "---",
  "",
  "| a | b |",
  "|---|---|",
  "| 1 | 2 |",
  "",
  "A body horizontal rule and a table above stress the frontmatter/GFM handling. " +
    "Closing paragraph long enough to clear the minimum body length the route enforces for real posts, " +
    "with a second sentence to be safe and a third for good measure.",
].join("\n");

async function main() {
  // Publishes now ping the studio Telegram — mute it for QA runs so the team
  // chat never sees dummy posts (sendTelegram no-ops without the token).
  process.env.TELEGRAM_BOT_TOKEN = "";

  // Fresh ground: remove leftovers from a previous (possibly crashed) run.
  const leftover = await openPrFor(BRANCH);
  if (leftover) await closePr(leftover);
  await deleteBranch(BRANCH).catch(() => {});

  console.log("Article publish suite\n");

  await test("rejects a missing/too-short body (400)", async () => {
    const r = await callRoute("POST", "/api/publish/article", { title: "X", body: "too short" });
    expect(r.status === 400, `got ${r.status}: ${r.text}`);
  });

  await test("rejects an invalid slug (400)", async () => {
    const r = await callRoute("POST", "/api/publish/article", {
      title: "ok title",
      slug: "Bad Slug!",
      body: BODY,
    });
    expect(r.status === 400, `got ${r.status}: ${r.text}`);
  });

  await test("rejects non-JSON input (400)", async () => {
    const r = await callRoute("POST", "/api/publish/article", "not json {{{");
    expect(r.status === 400, `got ${r.status}: ${r.text}`);
  });

  await test("409 on a slug already published on dev", async () => {
    const r = await callRoute("POST", "/api/publish/article", {
      title: "Duplicate",
      slug: "aws-cost-engineering-2026",
      body: BODY,
    });
    expect(r.status === 409, `got ${r.status}: ${r.text}`);
  });

  let prNumber = 0;
  await test("publishes a dummy draft article (cover + PR to dev)", async () => {
    const r = await callRoute("POST", "/api/publish/article", {
      title: TITLE,
      slug: SLUG,
      tags: ["QA", " Testing ", "qa", "", "meta", "one", "two", "three"], // dupes/blanks/case/overflow
      excerpt: 'A "quoted" excerpt for the QA suite.',
      imageBrief:
        "a tiny robot quality inspector stamping paper boats with green ticks in a harbour-side workshop",
      body: BODY,
      draft: true,
      inlineImages: 1,
    });
    expect(r.status === 200, `got ${r.status}: ${r.text}`);
    expect(r.json?.slug === SLUG, `slug mismatch: ${r.json?.slug}`);
    expect(String(r.json?.prUrl).includes("/pull/"), `no PR url: ${r.json?.prUrl}`);
    expect(String(r.json?.cover).startsWith("data:image/jpeg;base64,"), "no cover preview");
    expect(Array.isArray(r.json?.inline) && (r.json!.inline as string[]).length === 1, "no inline preview");
    prNumber = Number(String(r.json?.prUrl).split("/pull/")[1]);
    note(`PR #${prNumber}`);
  });

  await test("PR branch carries a well-formed markdown file", async () => {
    const md = (await landingFile(BRANCH, `content/blog/${SLUG}.md`))?.toString("utf8");
    expect(md, "markdown file missing from branch");
    expect(md.startsWith("---\n"), "no frontmatter open");
    expect(md.includes(`title: ${JSON.stringify(TITLE)}`), "title not escaped/present");
    expect(md.includes(`cover: "/blog/${SLUG}/cover.jpg"`), "cover path missing");
    expect(md.includes("draft: true"), "draft flag missing");
    const tagsLine = md.split("\n").find((l) => l.startsWith("tags:")) ?? "";
    expect(tagsLine.includes('"qa"') && tagsLine.includes('"testing"'), `tags not normalized: ${tagsLine}`);
    expect(!tagsLine.includes('""'), `blank tag survived: ${tagsLine}`);
    const fmEnd = md.indexOf("\n---\n", 4);
    expect(fmEnd > 0, "frontmatter never closes");
    expect(md.slice(fmEnd + 5).includes("## A section heading"), "body content missing");
  });

  await test("PR branch carries a real JPEG cover", async () => {
    const img = await landingFile(BRANCH, `public/blog/${SLUG}/cover.jpg`);
    expect(img, "cover missing from branch");
    expect(img.length > 20_000, `cover suspiciously small: ${img.length}B`);
    expect(img[0] === 0xff && img[1] === 0xd8, "not a JPEG");
  });

  await test("inline illustration lands in the branch and in the body", async () => {
    const img = await landingFile(BRANCH, `public/blog/${SLUG}/inline-1.jpg`);
    expect(img, "inline image missing from branch");
    expect(img[0] === 0xff && img[1] === 0xd8, "inline image not a JPEG");
    const md = (await landingFile(BRANCH, `content/blog/${SLUG}.md`))!.toString("utf8");
    expect(md.includes(`](/blog/${SLUG}/inline-1.jpg)`), "inline image not referenced in the body");
    const fmEnd = md.indexOf("\n---\n", 4);
    expect(md.indexOf(`inline-1.jpg`) > fmEnd, "inline image reference sits in the frontmatter");
  });

  await test("409 while an open PR already claims the slug", async () => {
    const r = await callRoute("POST", "/api/publish/article", {
      title: TITLE,
      slug: SLUG,
      body: BODY,
    });
    expect(
      r.status === 409,
      `expected 409 for pending-PR duplicate, got ${r.status}: ${r.text.slice(0, 120)}`,
    );
  });

  // Teardown
  if (prNumber) await closePr(prNumber);
  await deleteBranch(BRANCH).catch(() => {});
  // Any accidental duplicate branch from the pending-PR test:
  for (const suffix of ["-2", "-3"]) {
    const extra = await openPrFor(`${BRANCH}${suffix}`);
    if (extra) await closePr(extra);
    await deleteBranch(`${BRANCH}${suffix}`).catch(() => {});
  }
  note("teardown: PR closed, branches deleted");

  finish("Article publish suite");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
