// Generates the audit documents from the harness's raw data.
//
// The deliverables in section 7 are generated, never hand-maintained, so a
// document and the measurement behind it cannot disagree. Re-run after every
// sweep: `npx tsx scripts/ix-report.mts`.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { ROUTES, DOCUMENT_ROUTES } from "../tests/interaction/routes";

const RAW = "docs/audit/interaction/raw";
const OUT = "docs/audit/interaction";

const read = <T>(name: string): T[] => {
  const p = `${RAW}/${name}`;
  if (!existsSync(p)) return [];
  return JSON.parse(readFileSync(p, "utf8")) as T[];
};

type ViewportRow = {
  project: string;
  width: number;
  path: string;
  name: string;
  status: number;
  errorBoundary: boolean;
  consoleErrors: string[];
  scrollableBy: number;
  cls: number;
  targetCount: number;
  undersizedAA: { n: string; w: number; h: number; gap: number | null }[];
  underTouch44: number;
};
type AxeRow = {
  path: string;
  name: string;
  state: string;
  total: number;
  violations: { id: string; impact: string; help: string; nodes: number }[];
};
type KeyRow = {
  path: string;
  stops: number;
  tabOrderRegressions: number;
  stopsWithoutVisibleRing: number;
  firstTab: { text: string; visibleOnFocus: boolean } | null;
};
type ModalityRow = Record<string, unknown> & { check: string };
type OverlayRow = Record<string, unknown> & { name: string; opened: boolean };
type PerfRow = {
  route: string;
  label: string;
  clicked: boolean;
  worstEventMs: number;
  budget150: boolean | null;
  longTasks: unknown[];
};

const viewport = read<ViewportRow>("viewport.json");
const axe = read<AxeRow>("axe.json");
const keyboard = read<KeyRow>("keyboard.json");
const modality = read<ModalityRow>("modality.json");
const overlay = read<OverlayRow>("overlay.json");
const perf = read<PerfRow>("perf.json");

const widths = [...new Set(viewport.map((r) => r.width))].sort((a, b) => a - b);
const stamp = new Date().toISOString().slice(0, 10);

// ——— INVENTORY.md ———
{
  const lines: string[] = [
    "# Screen inventory",
    "",
    `Generated from \`tests/interaction/routes.ts\` on ${stamp}. Do not edit by hand:`,
    "`enumerated-routes.spec.ts` fails when this and the filesystem router disagree,",
    "and the document is regenerated by `npx tsx scripts/ix-report.mts`.",
    "",
    "## 2.1 Screens",
    "",
    "| Path | Name | Surface | Auth | Needs | Purpose |",
    "| --- | --- | --- | --- | --- | --- |",
  ];
  for (const r of [...ROUTES, ...DOCUMENT_ROUTES]) {
    lines.push(
      `| \`${r.path}\` | ${r.name} | ${r.surface} | ${r.auth} | ${r.needs ?? "nothing"} | ${r.purpose} |`,
    );
  }
  lines.push(
    "",
    `**${ROUTES.length} page routes** plus **${DOCUMENT_ROUTES.length} document route** rendered by a route handler.`,
    "",
    "## Interactive elements per screen",
    "",
    "Counted by the harness at 1440px, from the live DOM rather than from source,",
    "so a control that renders conditionally is counted only when it actually renders.",
    "",
    "| Path | Interactive elements | Tab stops | Under 44px on touch |",
    "| --- | ---: | ---: | ---: |",
  );
  for (const r of ROUTES) {
    const wide = viewport.find((x) => x.path === r.path && x.width === 1440);
    const kb = keyboard.find((x) => x.path === r.path);
    const touch = modality.find(
      (x) => x.check === "touch targets" && (x as { path?: string }).path === r.path,
    ) as { under44?: number; total?: number } | undefined;
    lines.push(
      `| \`${r.path}\` | ${wide?.targetCount ?? "?"} | ${kb?.stops ?? "?"} | ${touch?.under44 ?? "?"} of ${touch?.total ?? "?"} |`,
    );
  }
  const totalTargets = ROUTES.reduce(
    (n, r) => n + (viewport.find((x) => x.path === r.path && x.width === 1440)?.targetCount ?? 0),
    0,
  );
  lines.push("", `**${totalTargets} interactive elements** across the console at 1440px.`, "");
  writeFileSync(`${OUT}/INVENTORY.md`, lines.join("\n"));
}

// ——— VIEWPORT-MATRIX.md ———
{
  const lines: string[] = [
    "# Viewport matrix",
    "",
    `Generated ${stamp}. Every route at every width in section 5.1, plus a`,
    "640x360 landscape phone. `OK` means: HTTP under 400, no error boundary, no",
    "horizontal scroll, no console error.",
    "",
    "Screenshots are under `screens/<project>/<route>.png`.",
    "",
    `| Route | ${widths.map((w) => `${w}`).join(" | ")} |`,
    `| --- | ${widths.map(() => "---").join(" | ")} |`,
  ];
  for (const r of [...ROUTES, ...DOCUMENT_ROUTES]) {
    const cells = widths.map((w) => {
      const row = viewport.find((x) => x.path === r.path && x.width === w);
      if (!row) return "-";
      const problems: string[] = [];
      if (row.status >= 400) problems.push(`${row.status}`);
      if (row.errorBoundary) problems.push("boundary");
      if (row.scrollableBy > 0) problems.push(`+${row.scrollableBy}px`);
      if (row.consoleErrors.length) problems.push(`${row.consoleErrors.length} err`);
      return problems.length ? problems.join(" ") : "OK";
    });
    lines.push(`| \`${r.path}\` | ${cells.join(" | ")} |`);
  }
  const bad = viewport.filter((r) => r.scrollableBy > 0);
  lines.push(
    "",
    `**Horizontal overflow: ${bad.length} of ${viewport.length} measurements.**`,
    bad.length
      ? bad.map((b) => `- \`${b.path}\` at ${b.width}px scrolls ${b.scrollableBy}px`).join("\n")
      : "None.",
    "",
    "## Layout shift",
    "",
    `Worst CLS across all routes and widths: ${Math.max(...viewport.map((r) => r.cls)).toFixed(4)}.`,
    "The budget in section 5 is 0.02 on interaction.",
    "",
  );
  writeFileSync(`${OUT}/VIEWPORT-MATRIX.md`, lines.join("\n"));
}

// ——— MODALITY-AUDIT.md ———
{
  const hover = modality.find((r) => r.check === "hover dependency") as
    | { hoverRevealed: unknown[]; unguardedHoverRules: string[]; unguardedCount: number }
    | undefined;
  const targets = modality.filter((r) => r.check === "touch targets") as unknown as {
    path: string;
    total: number;
    under44: number;
    underAA24: number;
    crowdedUnder8px: number;
    worst: { name: string; w: number; h: number; gap: number | null }[];
  }[];

  const lines: string[] = [
    "# Modality audit",
    "",
    `Generated ${stamp}. Touch measurements come from WebKit at iPhone 15`,
    "dimensions, which is real Safari rather than Chromium pretending.",
    "",
    "## Hover dependency (section 3.3)",
    "",
    `Affordances revealed only by hover: **${hover?.hoverRevealed.length ?? "?"}**.`,
    "",
    `Unguarded \`:hover\` rules, which produce sticky hover on touch: **${hover?.unguardedCount ?? "?"}**.`,
    "A touch device applies these on tap and leaves them applied until something",
    "else is tapped, so a row stays lit after the finger has gone.",
    "",
    ...(hover?.unguardedHoverRules ?? []).map((s) => `- \`${s}\``),
    "",
    "## Touch targets (section 3.2)",
    "",
    "WCAG 2.2 AA 2.5.8 asks 24x24 CSS px, with an exception when neighbours are",
    "far enough apart. Apple's HIG asks 44x44. Both are reported: `<24 AA` counts",
    "only targets that fail the criterion including its spacing exception.",
    "",
    "| Route | Targets | <44px | <24px AA | Neighbours under 8px |",
    "| --- | ---: | ---: | ---: | ---: |",
    ...targets
      .sort((a, b) => b.under44 - a.under44)
      .map(
        (t) =>
          `| \`${t.path}\` | ${t.total} | ${t.under44} | ${t.underAA24} | ${t.crowdedUnder8px} |`,
      ),
    "",
    `**Total: ${targets.reduce((n, t) => n + t.under44, 0)} targets under 44px, ` +
      `${targets.reduce((n, t) => n + t.underAA24, 0)} failing WCAG 2.5.8 outright.**`,
    "",
    "## Keyboard (section 3.5)",
    "",
    "| Route | Tab stops | Order jumps | Stops with no visible ring | Skip link visible on focus |",
    "| --- | ---: | ---: | ---: | --- |",
    ...keyboard.map(
      (k) =>
        `| \`${k.path}\` | ${k.stops} | ${k.tabOrderRegressions} | ${k.stopsWithoutVisibleRing} | ${
          k.firstTab?.visibleOnFocus ? "yes" : "**no**"
        } |`,
    ),
    "",
  ];
  writeFileSync(`${OUT}/MODALITY-AUDIT.md`, lines.join("\n"));
}

// ——— OVERLAY-AUDIT.md ———
{
  const lines: string[] = [
    "# Overlay audit",
    "",
    `Generated ${stamp}. Each overlay is opened by its real trigger and driven`,
    "through the section 3.4 checks. Rows appear twice where an overlay was",
    "measured in both Chromium and WebKit, and the two disagreeing is itself a",
    "finding.",
    "",
    "| Overlay | Opened | role | aria-modal | Focus moves in | Escape closes | Focus leaks in 15 tabs | Scroll lock | Shift from lock | Focus returned to body |",
    "| --- | --- | --- | --- | --- | --- | ---: | --- | ---: | --- |",
    ...overlay.map((o) => {
      const g = (k: string): string => {
        const v = (o as Record<string, unknown>)[k];
        return v === undefined || v === null ? "-" : String(v);
      };
      return `| ${o.name} | ${o.opened} | ${g("role")} | ${g("ariaModal")} | ${g("focusMovedIn")} | ${g("escapeClosed")} | ${g("focusEscapedDuring15Tabs")} | ${g("scrollLockApplied")} | ${g("layoutShiftFromScrollLock")} | ${g("focusReturnedToBody")} |`;
    }),
    "",
    "Checks in section 3.4 this harness does not yet cover, recorded rather than",
    "implied: click-outside protection on dirty forms, nesting, positioning and",
    "collision near viewport edges, toast stacking and timers, virtual keyboard",
    "behaviour, and route change with an overlay open.",
    "",
  ];
  writeFileSync(`${OUT}/OVERLAY-AUDIT.md`, lines.join("\n"));
}

// ——— PERCEIVED-PERF.md ———
{
  const lines: string[] = [
    "# Perceived performance",
    "",
    `Generated ${stamp}. Latency is the browser's own \`event\` timing entry, not`,
    "wall-clock around an await, so it measures the interaction rather than",
    "Playwright's round trip. Budget from section 3.6: 150ms, with anything over",
    "200ms a finding.",
    "",
    "| Route | Interaction | Clicked | Worst event | Within 150ms | Long tasks over 50ms |",
    "| --- | --- | --- | ---: | --- | ---: |",
    ...perf.map(
      (p) =>
        `| \`${p.route}\` | ${p.label} | ${p.clicked ? "yes" : "**no**"} | ${p.worstEventMs}ms | ${
          p.budget150 === null ? "not measured" : p.budget150 ? "yes" : "**no**"
        } | ${p.longTasks.length} |`,
    ),
    "",
    "## Layout shift",
    "",
    `Worst CLS observed on load, across every route and width: **${Math.max(
      ...viewport.map((r) => r.cls),
    ).toFixed(4)}**.`,
    "",
    "## Coverage gap",
    "",
    "These are load-time and single-click measurements. Section 3.6 also asks for",
    "debounce and cancellation behaviour, optimistic rollback, race conditions on",
    "rapid filter switching, and Slow 3G. None of those is covered yet.",
    "",
  ];
  writeFileSync(`${OUT}/PERCEIVED-PERF.md`, lines.join("\n"));
}

// ——— A11Y summary, folded into the findings input ———
{
  const byRule = new Map<string, { nodes: number; routes: Set<string>; impact: string; help: string }>();
  for (const row of axe) {
    for (const v of row.violations) {
      const e = byRule.get(v.id) ?? { nodes: 0, routes: new Set<string>(), impact: v.impact, help: v.help };
      e.nodes += v.nodes;
      e.routes.add(`${row.path}${row.state === "at rest" ? "" : ` (${row.state})`}`);
      byRule.set(v.id, e);
    }
  }
  const lines: string[] = [
    "# Accessibility scan",
    "",
    `Generated ${stamp}. axe-core against WCAG 2.0/2.1/2.2 A and AA, on every`,
    "route at rest and on every overlay the harness could open.",
    "",
    "| Rule | Impact | Nodes | Routes |",
    "| --- | --- | ---: | ---: |",
    ...[...byRule.entries()]
      .sort((a, b) => b[1].nodes - a[1].nodes)
      .map(([id, e]) => `| \`${id}\` | ${e.impact} | ${e.nodes} | ${e.routes.size} |`),
    "",
    `**${[...byRule.values()].reduce((n, e) => n + e.nodes, 0)} failing nodes across ${byRule.size} distinct rules.**`,
    "",
    "## Per route",
    "",
    "| Route | State | Nodes | Rules |",
    "| --- | --- | ---: | --- |",
    ...axe
      .filter((r) => r.total > 0)
      .sort((a, b) => b.total - a.total)
      .map(
        (r) =>
          `| \`${r.path}\` | ${r.state} | ${r.total} | ${r.violations.map((v) => v.id).join(", ")} |`,
      ),
    "",
  ];
  writeFileSync(`${OUT}/A11Y-SCAN.md`, lines.join("\n"));
}

process.stdout.write(
  `Wrote INVENTORY.md, VIEWPORT-MATRIX.md, MODALITY-AUDIT.md, OVERLAY-AUDIT.md, PERCEIVED-PERF.md, A11Y-SCAN.md\n`,
);
